CREATE TABLE "PLMGR"."LOGIN_TOKEN_LOG" 
   (	
    "CHANNEL_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"GAME_ID" NUMBER(4,0) NOT NULL ENABLE, 
	"VERSION" VARCHAR2(30) NOT NULL ENABLE, 
	"USER_ID" VARCHAR2(32) NOT NULL ENABLE, 
	"TOKEN" VARCHAR2(64) NOT NULL ENABLE, 
	"STATE" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE
   ) 
  TABLESPACE "PLMGR_USER01" ;
   COMMENT ON COLUMN "PLMGR"."LOGIN_TOKEN_LOG"."CHANNEL_ID" IS '渠道ID';
   COMMENT ON COLUMN "PLMGR"."LOGIN_TOKEN_LOG"."GAME_ID" IS '游戏ID';
   COMMENT ON COLUMN "PLMGR"."LOGIN_TOKEN_LOG"."VERSION" IS '版本';
   COMMENT ON COLUMN "PLMGR"."LOGIN_TOKEN_LOG"."USER_ID" IS '玩家ID';
   COMMENT ON COLUMN "PLMGR"."LOGIN_TOKEN_LOG"."TOKEN" IS 'token值';
   COMMENT ON COLUMN "PLMGR"."LOGIN_TOKEN_LOG"."STATE" IS '状态    0 未使用   1已使用';
   COMMENT ON TABLE "PLMGR"."LOGIN_TOKEN_LOG"  IS '记录二次登录验证的token';
   ALTER TABLE "PLMGR"."LOGIN_TOKEN_LOG" ADD CONSTRAINT "KEY" PRIMARY KEY ("CHANNEL_ID", "GAME_ID", "VERSION", "USER_ID") using index tablespace "PLMGR_USER01";